config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root to: 'posts#index'
  resources :users, only: :show do
    member do
      get :posts, :likes, :followees, :followers
    end
    resource :follows, only: [:create, :destroy]
  end
  resources :statuses, only: [:create, :destroy]
  resources :profiles, only: [:new, :create, :edit, :update]
  resources :introductions, only: [:new, :create, :edit, :update, :destroy]
  resources :targets, only: [:index, :create]
  resources :posts do
    resources :explanations, only: [:new, :create, :edit, :update, :destroy]
    resources :comments, only: [:index, :create]
    resource  :likes, only: [:create, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :profile, dependent: :destroy
  has_one :introduction, dependent: :destroy
  has_one :status, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :targets, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :follower, class_name: 'Follow', foreign_key: 'follower_id', dependent: :destroy
  has_many :followee, class_name: 'Follow', foreign_key: 'followee_id', dependent: :destroy
  has_many :followees, through: :follower, source: :followee # 自分がフォローしている人
  has_many :followers, through: :followee, source: :follower # 自分をフォローしている人

  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze

  validates_format_of :password, { with: PASSWORD_REGEX, messege: 'is invalid. Include both letters and numbers' }

  validates :nickname, presence: true
  validates :initial_savings, presence: true

  def current_savings
    # balance_total: userのこれまでの残高の合計
    balance_total = Post.joins(:balance).select('posts.*, balance.amount').where(user_id: id)&.sum(:amount)
    (initial_savings + balance_total)
  end

  def check_target_achievement
    target = targets&.last
    if target.present?
      if target.amount <= current_savings && target.completed == false
        target.update(completed: true)
      elsif target.amount > current_savings && target.completed == true
        target.update(completed: false)
      end
    end
  end

  def like?(post)
    like = likes.find_by(post_id: post.id)
    like.present?
  end

  def follow(other_user)
    follower.find_or_create_by(followee_id: other_user.id) unless self == other_user
  end

  def unfollow(other_user)
    follow = follower.find_by(followee_id: other_user.id)
    follow&.destroy
  end

  def following?(other_user)
    followees.include?(other_user)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    new_profile_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :move_to_profile_new
  before_action :set_user

  def show
    @profile = Profile.find_by(user_id: @user.id)
    @introduction = Introduction.find_by(user_id: @user.id)
    @target = @user.targets.find_by(completed: false)
    @current_savings = @user.current_savings
  end

  def posts
    @user_posts = @user.posts.order(created_at: :desc).includes(:explanation)
  end

  def likes
    likes = Like.where(user_id: @user.id).pluck(:post_id)
    @like_posts = Post.order(created_at: :desc).includes(:user, :explanation).find(likes)
  end

  def followees
    @followees = @user.followees
    redirect_to request.referer unless @followees.present?
  end

  def followers
    @followers = @user.followers
    redirect_to request.referer unless @followers.present?
  end

  private

  def move_to_profile_new
    redirect_to new_profile_path if user_signed_in? && current_user.profile.nil?
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/views/users/followees.html.erb
<div class="follows-index">
  <div class="follows">
    <%= render partial: 'shared/user', collection: @followees %>
  </div>
</div>

app/views/users/followers.html.erb
<div class="follows-index">
  <div class="follows">
    <%= render partial: 'shared/user', collection: @followers %>
  </div>
</div>

app/views/users/likes.html.erb
<div class="posts-index">
  <div class="posts">
    <%= render partial: 'shared/post', collection: @like_posts %>
  </div>
</div>

app/views/users/posts.html.erb
<div class="posts-index">
  <div class="posts">
    <%= render partial: 'shared/post', collection: @user_posts %>
  </div>
</div>

app/views/users/show.html.erb
<div class="users-show">
  <div class="user-show">

    <div class="user-info-top">
      <div class="user-info-top__left">
        <div class="user-info-icon">
          <span class="material-symbols-outlined">account_circle</span>
        </div>
      </div>
      <div class="user-info-top__right">
        <div class="user-info-top__right-top">
          <div class="user-info-top__right-top__left">
            <div class="user-info-top__right-top__flex">
              <div class="user-info-nickname">
                <%= @user.nickname %>
              </div>
              <% if current_user&.id == @user.id %>
              <div class="user-info-edit-account">
                <%= link_to "アカウント情報を編集", "#" %>
              </div>
              <% end %>
            </div>
          </div>
          <div class="user-info-top__right-top__right">
            <% if current_user&.id != @user.id %>
              <% if current_user&.following?(@user) %>
              <div class="user-info-following">
                <%= link_to "フォロー中", user_follows_path(@user), method: :delete %>
              </div>
              <% else %>
              <div class="user-info-follow">
                <%= link_to "フォローする", user_follows_path(@user), method: :post %>
              </div>
              <% end %>
            <% end %>
          </div>
        </div>
        <div class="user-info-top__right-middle">
          <div class="user-info-statements number">
            <%= link_to posts_user_path(@user) do %>
            投稿 <span><%= @user.posts.length %></span>件
            <% end %>
          </div>
          <div class="user-info-follower number">
            <%= link_to followers_user_path(@user) do %>
            フォロワー <span><%= @user.followers.length %></span>人
            <% end %>
          </div>
          <div class="user-info-followee number">
            <%= link_to followees_user_path(@user) do %>
            フォロー中 <span><%= @user.followees.length %></span>人
            <% end %>
          </div>
          <div class="user-info-likes number">
            <%= link_to "いいね一覧", likes_user_path(@user) %>
          </div>
        </div>
        <div class="user-info-top__right-bottom">
          <% if current_user&.id == @user.id %>
            <% if @target.present? %>
            <div class="user-info-target">
              貯金目標 :　<span><%= @target.deadline.strftime("%Y年%-m月") %>までに<%= @target.amount.to_s(:delimited) %>円貯める！</span>
            </div>
            <% else %>
            <div class="user-info-target target-nil">
              現在、貯金目標額は未設定です。
            </div>
            <% end %>
          <div class="user-info-edit-target">
            <%= link_to "目標金額を設定・編集", targets_path %>
          </div>
          <% end %>
        </div>
      </div>
    </div>

    <div class="user-info-bottom">
      <div class="user-info-bottom__left">
        <table class="user-info-profile">
          <tr class="user-info-prefecture">
            <td class="td-profile-label">居住地域</td>
            <td class="td-profile">:　<%= @profile.prefecture.name %></td>
          </tr>
          <tr class="user-info-household">
            <td class="td-profile-label">世帯構成</td>
            <td class="td-profile">:　<%= @profile.household.name %></td>
          </tr>
          <tr class="user-info-age">
            <td class="td-profile-label">年齢層</td>
            <td class="td-profile">:　<%= @profile.age.name %></td>
          </tr>
          <tr class="user-info-gender">
            <td class="td-profile-label">性別</td>
            <td class="td-profile">:　<%= @profile.gender.name %></td>
          </tr>
          <tr class="user-info-annual_income">
            <td class="td-profile-label">年収幅</td>
            <td class="td-profile">:　<%= @profile.annual_income.name %></td>
          </tr>
          <% if @profile.monthly_target %>
          <tr class="user-info-monthly_target">
            <td class="td-profile-label">月の貯金目標額</td>
            <td class="td-profile">:　<%= @profile.monthly_target.to_s(:delimited) %>円</td>
          </tr>
          <% end %>
        </table>
        <% if current_user&.id == @user.id %>
          <div class="user-info-edit-profile">
            <%= link_to "プロフィールを編集", edit_profile_path(@profile) %>
          </div>
        <% end %>
        <% if @user.status.present? || current_user&.id == @user.id %>
          <table>
            <tr class="user-info-initial_savings">
              <td class="td-profile-label">登録時の貯金額</td>
              <td class="td-profile">:　<%= @user.initial_savings.to_s(:delimited) %>円</td>
            </tr>
            <tr class="user-info-current_savings">
              <td class="td-profile-label">現在の貯金額</td>
              <td class="td-profile">:　<%= @current_savings.to_s(:delimited) %>円</td>
            </tr>
          </table>
        <% end %>
        <% if current_user&.id == @user.id %>
          <% if @user.status.present? %>
            <div class="public-private">
              <div class="link-nil">
                <span class="material-symbols-outlined">public</span>
                <span class="nil-desc nil-public">貯金額公開中</span>
              </div>
              <div class="link-present">
                <%= link_to status_path(@user.status), method: :delete, class: "public-icon" do %>
                <span class="material-symbols-outlined">lock</span>
                <span class="present-desc">非公開にする</span>
                <% end %>
              </div>
            </div>
          <% else %>
            <div class="public-private">
              <div class="link-present">
                <%= link_to statuses_path, method: :post, class: "public-icon" do %>
                <span class="material-symbols-outlined">public</span>
                <span class="present-desc public-desc">　公開する　</span>
                <% end %>
              </div>
              <div class="link-nil">
                <span class="material-symbols-outlined">lock</span>
                <span class="nil-desc">貯金額非公開</span>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>

      <div class="user-info-bottom__right">
        <div class="user-info-introduction">
          <% if @introduction&.title1 %>
          <div class="introduction-title title1">
            ★ <%= @introduction&.title1 %>
          </div>
          <% end %>
          <div class="introduction-content content1">
            <% if @introduction&.text1.nil? %>
            <%= @introduction&.text1 %>
            <% else %>
            <%= safe_join(@introduction&.text1.split("\n"),tag(:br)) %>
            <% end %>
          </div>
          <% if @introduction&.title2.present? %>
          <div class="introduction-title title2">
            ★ <%= @introduction&.title2 %>
          </div>
          <% end %>
          <div class="introduction-content content2">
            <% if @introduction&.text2.nil? %>
            <%= @introduction&.text2 %>
            <% else %>
            <%= safe_join(@introduction&.text2.split("\n"),tag(:br)) %>
            <% end %>
          </div>
        </div>
        <% if current_user&.id == @user.id %>
          <% if @introduction.present? %>
          <div class="introduction-present">
            <div class="edit-introduction">
              <%= link_to "自己紹介を編集", edit_introduction_path(@introduction) %>
            </div>
            <div class="destroy-introduction">
              <%= link_to "自己紹介を削除", introduction_path(@introduction), method: :delete %>
            </div>
          </div>
          <% else %>
          <div class="create-introduction">
            <%= link_to "自己紹介を登録", new_introduction_path %>
          </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>