config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root to: 'posts#index'
  resources :users, only: :show do
    member do
      get :posts, :likes, :followees, :followers
    end
    resource :follows, only: [:create, :destroy]
  end
  resources :statuses, only: [:create, :destroy]
  resources :profiles, only: [:new, :create, :edit, :update]
  resources :introductions, only: [:new, :create, :edit, :update, :destroy]
  resources :targets, only: [:index, :create]
  resources :posts do
    resources :explanations, only: [:new, :create, :edit, :update, :destroy]
    resources :comments, only: [:index, :create]
    resource  :likes, only: [:create, :destroy]
  end
end

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_explanation_form.html.erb
<div class="form-group">
  <div class='form-text-wrap'>
    <label class="form-text"></label>
  </div>
  <%= f.text_area :text, placeholder: "例：その他出費の内訳 など" %>
</div>

app/views/shared/_introduction_form.html.erb
<div class="form-group">
  <div class='form-text-wrap'>
    <label class="form-text">タイトル1</label>
  </div>
  <%= f.text_field :title1, placeholder: "例：目標金額を達成したらやりたいこと" %>
</div>
<div class="form-group">
  <div class='form-text-wrap'>
    <label class="form-text">内容1</label>
  </div>
  <%= f.text_area :text1 %>
</div>
<div class="form-group">
  <div class='form-text-wrap'>
    <label class="form-text">タイトル2</label>
  </div>
  <%= f.text_field :title2, placeholder: "例：お金を貯めるために工夫していること" %>
</div>
<div class="form-group">
  <div class='form-text-wrap'>
    <label class="form-text">内容2</label>
  </div>
  <%= f.text_area :text2 %>
</div>

app/views/shared/_post.html.erb
<div class="post-index">
  <div class='pie-chart-index' >
    <%= link_to " #{post.user.nickname}", user_path(post.user), class: "pie-user-name" %>
    <%= link_to post_path(post) do %>
      <div class="pie-year-month-index">
        <%= post.month.strftime("%Y年%-m月") %>
      </div>
      <div class="pie-chart">
        <%= pie_chart post.chart_items,
                      width: '445px',
                      height: '250px',
                      colors: ['#fabea7','#94bcb7','#fdbf64','#8aa3b9','#fff700','#aeb5dc','#e5b7be','#d0e39b'] %>
      </div>
      <div class="expenses-total-table">
        <table>
          <tr class="expenses-total">
            <td>支出額合計: </td>
            <td><%= post.expenses.to_s(:delimited) %>円</td>
          </tr>
        </table>
      </div>
      <% if post.explanation.present? %>
      <div class="post-explanation-index">
        <%= safe_join(post.explanation.text.split("\n"),tag(:br)) %>
      </div>
      <% else %>
      <div class="post-explanation-nil">
      </div>
      <% end %>
    <% end %>
    <div class="post-index-icons">
      <%= render partial: 'shared/post_icons', locals: { post: post } %>
    </div>
  </div>
</div>

app/views/shared/_post_form.html.erb
<div class="form-group">
  <div class='form-text-wrap'>
    <label class="form-text">年月</label>
  </div>
  <%= f.date_select(
      :month,
      class:'month-select',
      use_month_numbers: true,
      selected: Time.now,
      start_year: (Time.now.year - 1),
      end_year: (Time.now.year + 1),
      discard_day: true
      ) %>
</div>
<div class="form-group">
  <div class='form-text-wrap'>
    <label class="form-text">月の手取り</label>
  </div>
  <%= f.number_field :net_income, data: { autonumeric: true } %>
</div>
<div class="form-group">
  <div class='form-text-wrap'>
    <label class="form-text">住宅費</label>
  </div>
  <%= f.number_field :housing, data: { autonumeric: true } %>
</div>
<div class="form-group">
  <div class='form-text-wrap'>
    <label class="form-text">水道光熱費</label>
  </div>
  <%= f.number_field :utilities, data: { autonumeric: true } %>
</div>
<div class="form-group">
  <div class='form-text-wrap'>
    <label class="form-text">通信費</label>
  </div>
  <%= f.number_field :internet, data: { autonumeric: true } %>
</div>
<div class="form-group">
  <div class='form-text-wrap'>
    <label class="form-text">食費</label>
  </div>
  <%= f.number_field :groceries, data: { autonumeric: true } %>
</div>
<div class="form-group">
  <div class='form-text-wrap'>
    <label class="form-text">日用品費</label>
  </div>
  <%= f.number_field :daily_necessities, data: { autonumeric: true } %>
</div>
<div class="form-group">
  <div class='form-text-wrap'>
    <label class="form-text">娯楽費</label>
  </div>
  <%= f.number_field :entertainment, data: { autonumeric: true } %>
</div>
<div class="form-group">
  <div class='form-text-wrap'>
    <label class="form-text">その他出費</label>
  </div>
  <%= f.number_field :others, data: { autonumeric: true } %>
</div>

app/views/shared/_post_icons.html.erb
<div class="post-icons">
  <div class="post-icons__left">
    <div class="post-comments">
      <%= link_to post_comments_path(post), class: "comments-icon" do %>
      <span class="material-symbols-outlined">chat</span>
      <% end %>
    </div>
    <div class="comments-count post-count">
      <%= post.comments.length %>
    </div>
  </div>
  <div class="post-icons__right">
    <div class="post-likes">
      <% if current_user&.like?(post) %>
        <%= link_to post_likes_path(post), method: :delete, class: "likes-icon" do %>
        <span class="material-symbols-outlined">thumb_up</span>
        <% end %>
      <% else %>
        <%= link_to post_likes_path(post), method: :post, class: "likes-icon-gray" do %>
        <span class="material-symbols-outlined">thumb_up</span>
        <% end %>
      <% end %>
    </div>
    <div class="likes-count post-count">
      <%= post.likes.length %>
    </div>
  </div>
</div>

app/views/shared/_profile_form.html.erb
<div class="form-group">
  <div class='form-text-wrap'>
    <label class="form-text">年齢</label>
  </div>
  <%= f.collection_select(:age_id, Age.all, :id, :name, {include_blank: "---"}, {class:"select-box"}) %>
</div>
  <div class="form-group">
  <div class='form-text-wrap'>
    <label class="form-text">性別</label>
  </div>
  <%= f.collection_select(:gender_id, Gender.all, :id, :name, {include_blank: "---"}, {class:"select-box"}) %>
</div>
<div class="form-group">
  <div class='form-text-wrap'>
    <label class="form-text">世帯構成</label>
  </div>
  <%= f.collection_select(:household_id, Household.all, :id, :name, {include_blank: "---"}, {class:"select-box"}) %>
</div>
<div class="form-group">
  <div class='form-text-wrap'>
    <label class="form-text">年収</label>
  </div>
  <%= f.collection_select(:annual_income_id, AnnualIncome.all, :id, :name, {include_blank: "---"}, {class:"select-box"}) %>
</div>
<div class="form-group">
  <div class='form-text-wrap'>
    <label class="form-text">在住の都道府県</label>
  </div>
  <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {include_blank: "---"}, {class:"select-box"}) %>
</div>
<div class="form-group">
  <div class='form-text-wrap'>
    <label class="form-text">毎月の貯金目標額</label>
  </div>
  <%= f.number_field :monthly_target, class:"input-default", id:"monthly_target" %>
</div>

app/views/shared/_user.html.erb
<div class="follow-index">
  <div class="follow-index__left">
    <%= link_to user.nickname, user_path(user), class: "follow-user-name" %>
  </div>
  <div class="follow-index__right">
  <% if current_user&.id != user.id %>
    <% if current_user&.following?(user) %>
    <div class="user-info-following follow-user">
      <%= link_to "フォロー中", user_follows_path(user), method: :delete %>
    </div>
    <% else %>
    <div class="user-info-follow follow-user">
      <%= link_to "フォローする", user_follows_path(user), method: :post %>
    </div>
    <% end %>
  <% end %>
  </div>
</div>