config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root to: 'posts#index'
  resources :users, only: :show do
    member do
      get :posts, :likes, :followees, :followers
    end
    resource :follows, only: [:create, :destroy]
  end
  resources :statuses, only: [:create, :destroy]
  resources :profiles, only: [:new, :create, :edit, :update]
  resources :introductions, only: [:new, :create, :edit, :update, :destroy]
  resources :targets, only: [:index, :create]
  resources :posts do
    resources :explanations, only: [:new, :create, :edit, :update, :destroy]
    resources :comments, only: [:index, :create]
    resource  :likes, only: [:create, :destroy]
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_one :balance, dependent: :destroy
  has_one :fixed_profile, dependent: :destroy
  has_one :explanation, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :month, uniqueness: { scope: :user }
  validates :month, :net_income, :housing, :utilities, :internet,
            :groceries, :daily_necessities, :entertainment, :others,
            presence: true
  validates :net_income, :housing, :utilities, :internet,
            :groceries, :daily_necessities, :entertainment, :others,
            numericality: { only_integer: true }

  def chart_items
    { '家賃': housing, '水道光熱費': utilities, '通信費': internet, '食費': groceries,
      '日用品費': daily_necessities, '娯楽費': entertainment, 'その他出費': others, '貯金': balance.amount }
  end

  def expenses
    (housing + utilities + internet + groceries + daily_necessities + entertainment + others)
  end

  def calculate_balance
    expenses
    (net_income - expenses)
  end

  def saving_rate
    (balance.amount.to_f / net_income * 100).round
  end

  def current_savings
    # balance_total: 投稿した収支の年月までの、投稿者の残高の合計
    balance_total = Post.joins(:balance).select('posts.*, balance.amount').where(user_id: user_id).where('month <= ?', month.to_date)&.sum(:amount)
    (user.initial_savings + balance_total)
  end

  def check_target_achievement_when_create
    target.update(completed: true) if fixed_profile.target.present? && fixed_profile.target <= current_savings
  end

  def check_target_achievement_when_update
    target = user.targets&.last
    if fixed_profile.target.present? && fixed_profile.target == target.amount
      if fixed_profile.target <= current_savings && target.completed == false
        target.update(completed: true)
      elsif fixed_profile.target > current_savings && target.completed == true
        target.update(completed: false)
      end
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit]
  before_action :move_to_profile_new
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :move_to_index, only: [:edit, :destroy]

  def index
    @posts = Post.order(created_at: :desc).includes(:user, :explanation)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      create_balance_and_fixed_profile
      @post.check_target_achievement_when_create
      redirect_to new_post_explanation_path(@post)
    else
      render :new
    end
  end

  def show
    @current_savings = @post.current_savings
    @fixed_profile = @post.fixed_profile
    @explanation = @post.explanation
  end

  def edit
  end

  def update
    if @post.update(post_params)
      update_balance
      @post.check_target_achievement_when_update
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    @post.user.check_target_achievement
    redirect_to root_path
  end

  private

  def move_to_profile_new
    redirect_to new_profile_path if user_signed_in? && current_user.profile.nil?
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def move_to_index
    redirect_to root_path if current_user.id != @post.user_id
  end

  def create_balance_and_fixed_profile
    Balance.create(amount: @post.calculate_balance, post_id: @post.id)
    profile = current_user.profile
    target = current_user.targets.find_by(completed: false)
    FixedProfile.create(
      age: profile.age.name, gender: profile.gender.name, household: profile.household.name,
      annual_income: profile.annual_income.name, prefecture: profile.prefecture.name,
      monthly_target: profile.monthly_target, target: target&.amount, post_id: @post.id
    )
  end

  def update_balance
    balance = Balance.find(@post.id)
    balance.update(amount: @post.calculate_balance)
  end

  def post_params
    params.require(:post).permit(
      :month, :net_income, :housing, :utilities, :internet,
      :groceries, :daily_necessities, :entertainment, :others
    ).merge(user_id: current_user.id)
  end
end

app/views/posts/edit.html.erb
<%= form_with model: @post, class: 'registration-main', local: true do |f| %>
<div class='form-wrap'>
  <div class='form-header'>
    <h1 class='form-header-text'>
      収支の編集
    </h1>
    <div class="edit-notice">
      ※編集後もプロフィール情報及び目標金額は、最初に投稿した時点のものとなります。
    </div>
  </div>

  <%= render 'shared/error_messages', model: f.object %>
  <%= render 'shared/post_form', f: f %>

  <div class='form-btn'>
  <%= f.submit "収支の更新" ,class:"btn" %>
  </div>
</div>
<% end %>

app/views/posts/index.html.erb
<div class="posts-index">
  <div class="posts">
    <%= render partial: 'shared/post', collection: @posts %>
  </div>
</div>

app/views/posts/new.html.erb
<%= form_with model: @post, class: 'registration-main', local: true do |f| %>
<div class='form-wrap'>
  <div class='form-header'>
    <h1 class='form-header-text'>
      収支の入力
    </h1>
  </div>

  <%= render 'shared/error_messages', model: f.object %>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">年月</label>
    </div>
    <%= f.date_select(
        :month,
        class:'month-select',
        use_month_numbers: true,
        selected: Time.now,
        start_year: (Time.now.year - 1),
        end_year: (Time.now.year + 1),
        discard_day: true
        ) %>
  </div>
    <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">手取り収入</label>
    </div>
    <%= f.text_area :net_income %>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">住宅費</label>
    </div>
    <%= f.text_area :housing %>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">水道光熱費</label>
    </div>
    <%= f.text_area :utilities %>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">通信費</label>
    </div>
    <%= f.text_area :internet %>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">食費</label>
    </div>
    <%= f.text_area :groceries %>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">日用品費</label>
    </div>
    <%= f.text_area :daily_necessities %>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">娯楽費</label>
    </div>
    <%= f.text_area :entertainment %>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">その他出費</label>
    </div>
    <%= f.text_area :others %>
  </div>

  <br>
  <div class='register-btn'>
    <%= f.submit "収支投稿" ,class:"register-red-btn" %>
  </div>
</div>
<% end %>

app/views/posts/show.html.erb
<div class="posts-show">
  <div class="post-show">
    <div class="post-show-main">
      <div class="post-show__left" >
        <div class='pie-chart-show' >
          <%= pie_chart @post.chart_items,
                        width: '700px',
                        height: '350px',
                        colors: ['#fabea7','#94bcb7','#fdbf64','#8aa3b9','#fff700','#aeb5dc','#e5b7be','#d0e39b'] %>
        </div>
        <div class="monthly-saving">
          <% unless @post.balance.amount <= 0 %>
          <div class="monthly-saving__monthly-target">
          今月の貯金額は手取り<span>の <%= @post.saving_rate %>％、</span>
            <% if (@post.balance.amount >= @fixed_profile.monthly_target) %>
            <span>月の目標額 <%= @fixed_profile.monthly_target.to_s(:delimited) %>円 を達成！</span>
            <% else %>
            月の目標額 <%= @fixed_profile.monthly_target.to_s(:delimited) %>円 は未達成
            <% end %>
          </div>
          <% end %>
          <% if @fixed_profile.target.present? %>
          <div class="monthly-saving__target">
            <% if (@fixed_profile.target > @post.current_savings) %>
              ★貯金目標額の<%= @fixed_profile.target.to_s(:delimited) %>円まで、あと <strong><%= (@fixed_profile.target - @current_savings).to_s(:delimited) %>円</strong>★
            <% elsif (@fixed_profile.target <= @post.current_savings) %>
              <strong>貯金目標額の<%= @fixed_profile.target.to_s(:delimited) %>円を達成しました！</strong>🎉🎉🎉
            <% end %>
          </div>
          <% end %>
        </div>

        <div class="post-explanation-show">
          <div class="post-explanation-show__left">
            <% if @explanation.present? %>
              <div class="post-explanation">
                <%= safe_join(@explanation.text.split("\n"),tag(:br)) %>
              </div>
            <% else %>
              <% if current_user&.id == @post.user.id %>
              <div class="create-explanation">
                <%= link_to "収支の補足説明を追加", new_post_explanation_path(@post) %>
              </div>
              <% end %>
            <% end %>
          </div>
          <div class="post-explanation-show__right">
            <% if current_user&.id == @post.user.id %>
              <% if @explanation.present? %>
              <div class="edit-explanation">
                <%= link_to "説明を編集", edit_post_explanation_path(@post, @explanation) %>
              </div>
              <div class="destroy-explanation">
                <%= link_to "説明を削除", post_explanation_path(@post, @explanation), method: :delete %>
              </div>
              <% end %>
            <% end %>
          </div>
        </div>

        <%= render partial: 'shared/post_icons', locals: { post: @post } %>
      </div>

      <div class="post-show__right">
        <div class="pie-year-month-show">
          <%= @post.month.strftime("%Y年%-m月") %>
        </div>
        <table>
          <tr>
            <td class="td income">手取り収入</td>
            <td class="td price income"><%= @post.net_income.to_s(:delimited) %></td>
          </tr>
          <tr>
            <th class="th">支出費目</th>
            <th class="th">支出金額</th>
          </tr>
          <tr>
            <td class="td">家賃</td>
            <td class="td price"><%= @post.housing.to_s(:delimited) %></td>
          </tr>
          <tr>
            <td class="td">水道光熱費</td>
            <td class="td price"><%= @post.utilities.to_s(:delimited) %></td>
          </tr>
          <tr>
            <td class="td">通信費</td>
            <td class="td price"><%= @post.internet.to_s(:delimited) %></td>
          </tr>
          <tr>
            <td class="td">食費</td>
            <td class="td price"><%= @post.groceries.to_s(:delimited) %></td>
          </tr>
          <tr>
            <td class="td">日用品費</td>
            <td class="td price"><%= @post.daily_necessities.to_s(:delimited) %></td>
          </tr>
          <tr>
            <td class="td">娯楽費</td>
            <td class="td price"><%= @post.entertainment.to_s(:delimited) %></td>
          </tr>
          <tr>
            <td class="td">その他</td>
            <td class="td price"><%= @post.others.to_s(:delimited) %></td>
          </tr>
          <tr>
            <td class="td total">合計</td>
            <td class="td price total"><%= @post.expenses.to_s(:delimited) %></td>
          </tr>
          <tr>
            <td class="td saving">残高</td>
            <td class="td price saving"><%= @post.balance.amount.to_s(:delimited) %></td>
          </tr>
        </table>
        <% if current_user&.id == @post.user.id %>
        <div class="post-link">
          <div class="edit-post">
            <%= link_to "収支を編集", edit_post_path(@post) %>
          </div>
          <div class="destroy-post">
            <%= link_to "収支を削除", post_path(@post), method: :delete %>
          </div>
        </div>
        <% end %>
        <br>
        <div class="table-profile">
          <%= link_to " #{@post.user.nickname}", user_path(@post.user), class: "table-profile-name" %>
        </div>
        <div class="table-profile">
          <%= @fixed_profile.prefecture %> 在住
        </div>
        <div class="table-profile">
          <%= @fixed_profile.household %>
        </div>
        <div class="table-profile">
          <%= @fixed_profile.age %>
        </div>
        <div class="table-profile">
          <%= @fixed_profile.gender %>
        </div>
        <div class="table-profile">
          年収: <%= @fixed_profile.annual_income %>
        </div>
      </div>
    </div>
  </div>
</div>