config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root to: 'posts#index'
  resources :users, only: :show do
    member do
      get :posts, :likes, :followees, :followers
    end
    resource :follows, only: [:create, :destroy]
  end
  resources :statuses, only: [:create, :destroy]
  resources :profiles, only: [:new, :create, :edit, :update]
  resources :introductions, only: [:new, :create, :edit, :update, :destroy]
  resources :targets, only: [:index, :create]
  resources :posts do
    resources :explanations, only: [:new, :create, :edit, :update, :destroy]
    resources :comments, only: [:index, :create]
    resource  :likes, only: [:create, :destroy]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PilingUp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kanit:wght@100;300;500&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Outlined" rel="stylesheet">
    <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

<header class="header">
  <div class="inner">
    <div class="nav">
      <div class="nav__left">
        <%= link_to "PILING UP", root_path, class: :logo %>
      </div>
      <% if user_signed_in? %>
        <div class="nav__right">
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav__logout %>
          <% if current_page?(user_path(current_user)) %>
            <%= link_to "収支投稿", new_post_path, class: :nav__btn %>
          <% else %>
            <%= link_to "マイページ", user_path(current_user), class: :nav__btn %>
          <% end %>
        </div>
      <% else %>
        <div class="nav__right">
          <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
          <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
        </div>
      <% end %>
    </div>
  </div>
</header>

  <body>
    <%= yield %>
  </body>
</html>